name: Terraform CI/CD

on:
  push:
    branches:
      - main # Change this to the branch you want to trigger the workflow on

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Initialize Terraform
      run: terraform init

    - name: Plan Terraform changes
      run: terraform plan -input=false -out=tfplan

    - name: Apply Terraform changes
      run: terraform apply -input=false tfplan
      env:
        TF_CLI_ARGS: "-auto-approve"
